# Generated by Django 5.1.6 on 2025-03-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridients',
            new_name='Ingredients',
        ),
    ]
